apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: kafka-to-postgres-batch
  namespace: spark
spec:
  type: Python
  mode: cluster
  image: dave126/custom-spark:3.5.4-no-kerb
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/bitnami/spark/jobs/consume_kafka_to_postgres_batch.py
  deps:
    jars:
      - local:///opt/bitnami/spark/jars/spark-sql-kafka-0-10_2.12-3.5.4.jar
      - local:///opt/bitnami/spark/jars/kafka-clients-3.6.1.jar
      - local:///opt/bitnami/spark/jars/spark-token-provider-kafka-0-10_2.12-3.5.4.jar
      - local:///opt/bitnami/spark/jars/commons-pool2-2.11.1.jar
      - local:///opt/bitnami/spark/jars/postgresql-42.7.1.jar
  hadoopConf:
    "hadoop.security.authentication": "simple"
    "hadoop.security.authorization": "false"

  sparkConf:
    spark.kubernetes.namespace: spark
    spark.hadoop.hadoop.security.authentication: simple
    spark.hadoop.hadoop.security.authorization: "false"

  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20

  driver:
    labels: {}
    serviceAccount: spark
    cores: 1
    memory: 1g

  executor:
    serviceAccount: spark
    cores: 1
    instances: 2
    memory: 512m
    labels:
      version: 3.1.1
